"""Word list and cloze frames.

HOW TO REPLACE THE PLACEHOLDER
------------------------------
Do not edit this file. Build promptutils/words.json instead:

    python3 build_words.py --romanlens <Romanlens>/llm_logit_lens/data/langs \
        --model <model>                      # -> promptutils/words.json
    python3 build_controls.py --model <model>  # -> promptutils/controls.json

Selection order:
    LLAT_WORDS=placeholder    force the built-in list
    LLAT_WORDS=<path.json>    use that file
    promptutils/words.json    the default when present

THE LIST BELOW IS PLACEHOLDER DATA. The romanisations are plausible spellings
rather than IndicXlit output, and the cloze frames are literal translations
that may read oddly.

Fields per entry:
    en / fr / de        source-side surface forms
    hi / ta / ml        (native script, romanisation)
    cognate             True when the Indic word is an English loanword, so
                        target and English are phonetically near-identical
    cloze               {lang: sentence with ___ } frames
"""

_PLACEHOLDER_WORDS = [
    dict(en="flower", fr="fleur", de="Blume", cognate=False,
         hi=("फूल", "phool"), ta=("பூ", "poo"), ml=("പൂവ്", "poovu"),
         cloze={"en": "The bee landed on the ___",
                "hi": "मधुमक्खी ___ पर बैठी",
                "ta": "தேனீ ___ மீது அமர்ந்தது",
                "ml": "തേനീച്ച ___ മേൽ ഇരുന്നു"}),
    dict(en="water", fr="eau", de="Wasser", cognate=False,
         hi=("पानी", "paani"), ta=("தண்ணீர்", "thanneer"), ml=("വെള്ളം", "vellam"),
         cloze={"en": "She was thirsty and drank some ___",
                "hi": "उसे प्यास लगी और उसने ___ पिया",
                "ta": "அவளுக்கு தாகம் எடுத்தது, அவள் ___ குடித்தாள்",
                "ml": "അവൾക്ക് ദാഹിച്ചു, അവൾ ___ കുടിച്ചു"}),
    dict(en="book", fr="livre", de="Buch", cognate=False,
         hi=("किताब", "kitaab"), ta=("புத்தகம்", "puthagam"),
         ml=("പുസ്തകം", "pusthakam"),
         cloze={"en": "He opened the ___ and began to read",
                "hi": "उसने ___ खोली और पढ़ने लगा",
                "ta": "அவன் ___ திறந்து படிக்கத் தொடங்கினான்",
                "ml": "അവൻ ___ തുറന്ന് വായിക്കാൻ തുടങ്ങി"}),
    dict(en="sun", fr="soleil", de="Sonne", cognate=False,
         hi=("सूरज", "sooraj"), ta=("சூரியன்", "sooriyan"),
         ml=("സൂര്യൻ", "sooryan"),
         cloze={"en": "In the morning the ___ rises in the east",
                "hi": "सुबह ___ पूरब में उगता है",
                "ta": "காலையில் ___ கிழக்கில் உதிக்கும்",
                "ml": "രാവിലെ ___ കിഴക്ക് ഉദിക്കുന്നു"}),
    dict(en="mountain", fr="montagne", de="Berg", cognate=False,
         hi=("पहाड़", "pahaad"), ta=("மலை", "malai"), ml=("മല", "mala"),
         cloze={"en": "The climbers reached the top of the ___",
                "hi": "पर्वतारोही ___ की चोटी पर पहुँचे",
                "ta": "மலையேறுபவர்கள் ___ உச்சியை அடைந்தனர்",
                "ml": "പർവതാരോഹകർ ___ മുകളിൽ എത്തി"}),
    dict(en="fire", fr="feu", de="Feuer", cognate=False,
         hi=("आग", "aag"), ta=("நெருப்பு", "neruppu"), ml=("തീ", "thee"),
         cloze={"en": "They sat around the warm ___",
                "hi": "वे गर्म ___ के चारों ओर बैठे",
                "ta": "அவர்கள் சூடான ___ சுற்றி அமர்ந்தனர்",
                "ml": "അവർ ചൂടുള്ള ___ ചുറ്റും ഇരുന്നു"}),
    dict(en="house", fr="maison", de="Haus", cognate=False,
         hi=("घर", "ghar"), ta=("வீடு", "veedu"), ml=("വീട്", "veedu"),
         cloze={"en": "After work he returned to his ___",
                "hi": "काम के बाद वह अपने ___ लौटा",
                "ta": "வேலைக்குப் பிறகு அவன் தன் ___ திரும்பினான்",
                "ml": "ജോലി കഴിഞ്ഞ് അവൻ തന്റെ ___ മടങ്ങി"}),
    dict(en="night", fr="nuit", de="Nacht", cognate=False,
         hi=("रात", "raat"), ta=("இரவு", "iravu"), ml=("രാത്രി", "raathri"),
         cloze={"en": "The stars come out at ___",
                "hi": "तारे ___ को निकलते हैं",
                "ta": "நட்சத்திரங்கள் ___ வெளிவரும்",
                "ml": "നക്ഷത്രങ്ങൾ ___ പുറത്തുവരുന്നു"}),
    dict(en="milk", fr="lait", de="Milch", cognate=False,
         hi=("दूध", "doodh"), ta=("பால்", "paal"), ml=("പാൽ", "paal"),
         cloze={"en": "The child drank a glass of ___",
                "hi": "बच्चे ने एक गिलास ___ पिया",
                "ta": "குழந்தை ஒரு டம்ளர் ___ குடித்தது",
                "ml": "കുട്ടി ഒരു ഗ്ലാസ് ___ കുടിച്ചു"}),
    dict(en="tree", fr="arbre", de="Baum", cognate=False,
         hi=("पेड़", "ped"), ta=("மரம்", "maram"), ml=("മരം", "maram"),
         cloze={"en": "The bird built a nest in the ___",
                "hi": "पक्षी ने ___ में घोंसला बनाया",
                "ta": "பறவை ___ கூடு கட்டியது",
                "ml": "പക്ഷി ___ കൂട് ഉണ്ടാക്കി"}),
    # --- cognates: the Indic form IS the English word borrowed ------------
    dict(en="bus", fr="autobus", de="Bus", cognate=True,
         hi=("बस", "bas"), ta=("பேருந்து", "bus"), ml=("ബസ്", "bas"),
         cloze={"en": "She waited at the stop for the ___",
                "hi": "वह स्टॉप पर ___ का इंतज़ार करती रही",
                "ta": "அவள் நிறுத்தத்தில் ___ காத்திருந்தாள்",
                "ml": "അവൾ സ്റ്റോപ്പിൽ ___ കാത്തിരുന്നു"}),
    dict(en="hotel", fr="hôtel", de="Hotel", cognate=True,
         hi=("होटल", "hotel"), ta=("ஹோட்டல்", "hotel"), ml=("ഹോട്ടൽ", "hotel"),
         cloze={"en": "We stayed at a small ___ near the station",
                "hi": "हम स्टेशन के पास एक छोटे ___ में ठहरे",
                "ta": "நாங்கள் நிலையத்திற்கு அருகிலுள்ள ஒரு சிறிய ___ இல் தங்கினோம்",
                "ml": "ഞങ്ങൾ സ്റ്റേഷനടുത്തുള്ള ഒരു ചെറിയ ___ ൽ താമസിച്ചു"}),
    dict(en="coffee", fr="café", de="Kaffee", cognate=True,
         hi=("कॉफी", "coffee"), ta=("காபி", "coffee"), ml=("കാപ്പി", "coffee"),
         cloze={"en": "She ordered a cup of ___",
                "hi": "उसने एक कप ___ मंगाई",
                "ta": "அவள் ஒரு கப் ___ ஆர்டர் செய்தாள்",
                "ml": "അവൾ ഒരു കപ്പ് ___ ഓർഡർ ചെയ്തു"}),
    dict(en="mobile", fr="mobile", de="Handy", cognate=True,
         hi=("मोबाइल", "mobile"), ta=("மொபைல்", "mobile"),
         ml=("മൊബൈൽ", "mobile"),
         cloze={"en": "He forgot his ___ at home",
                "hi": "वह अपना ___ घर पर भूल गया",
                "ta": "அவன் தனது ___ வீட்டில் மறந்துவிட்டா",
                "ml": "അവൻ തന്റെ ___ വീട്ടിൽ മറന്നു"}),
]

# Unrelated common English nouns, matched on NOTHING. P(correct English word)
# versus P(one of these) is a coarse specificity check: if an arbitrary English
# word peaks just as high mid-stack, the hump means "Latin-script tokens are
# likely here" rather than "this concept was retrieved". build_controls.py
# produces a properly matched version (unigram frequency and |Start(w)|) in
# promptutils/controls.json, which takes priority when present.
EN_CONTROLS_RANDOM = ["window", "letter", "garden", "silver", "morning",
                      "paper", "river", "bridge", "candle", "basket",
                      "pocket", "harbour", "meadow", "lantern"]


def _load():
    """Returns (words, is_placeholder). Callers warn loudly on the placeholder
    so a figure can never be mistaken for a result."""
    import json
    import os

    here = os.path.dirname(os.path.abspath(__file__))
    env = os.environ.get("LLAT_WORDS", "").strip()
    if env.lower() == "placeholder":
        return _PLACEHOLDER_WORDS, True
    path = env or os.path.join(here, "words.json")
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            raw = json.load(f)
        words = []
        for w in raw:
            e = dict(w)
            # JSON has no tuples; restore the (native, roman) pairs
            for lg in ("hi", "ta", "ml"):
                if lg in e and isinstance(e[lg], list):
                    e[lg] = tuple(e[lg])
            words.append(e)
        return words, False
    return _PLACEHOLDER_WORDS, True


WORDS, IS_PLACEHOLDER = _load()